namespace Lotofacil.Loader.Application;

public enum ReasonStop
{
    COMPLETED_SUCCESS,
    EARLY_EXIT_NOT_BUSINESS_DAY,
    EARLY_EXIT_BEFORE_20H,
    EARLY_EXIT_ALREADY_LOADED_TODAY,
    EARLY_EXIT_ALREADY_ALIGNED,
    SAFE_STOP_WINDOW_EXPIRED,
    SAFE_STOP_CONCURRENCY_TABLE_ETAG,
    SAFE_STOP_CONCURRENCY_BLOB_CONFLICT,
    HARD_FAIL_CONFIG_INVALID,
    HARD_FAIL_API_AUTH,
    HARD_FAIL_API_SCHEMA,
    HARD_FAIL_GAP_NOT_FOUND_404,
    HARD_FAIL_STATE_INCONSISTENT_TABLE_GT_BLOB
}

