namespace Lotofacil.Loader.Application;

public enum ReasonStop
{
    COMPLETED_SUCCESS,
    SAFE_STOP_WINDOW_EXPIRED,
    SAFE_STOP_CONCURRENCY_TABLE_ETAG,
    SAFE_STOP_CONCURRENCY_BLOB_CONFLICT,
    HARD_FAIL_CONFIG_INVALID,
    HARD_FAIL_API_AUTH,
    HARD_FAIL_API_SCHEMA,
    HARD_FAIL_STATE_INCONSISTENT_TABLE_GT_BLOB
}
